import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { VISIT_TYPE_LABELS, VISIT_STATUS_LABELS, visitActions, type PedagogicalVisit } from '../src/types/pedagogicalVisit';
import { VisitAgenda } from '../src/components/dashboard/inspector/PedagogicalVisitPlanner';
import { readFileSync } from 'node:fs';
const visit = { id: 'synthetic', teacherId: 'T', inspectorId: 'A', status: 'SCHEDULED', visitType: 'GUIDANCE', teacherNotifiedAt: null, scheduledAt: '2098-10-08T09:00:00+01:00', academicYearId: '2098-2099', history: [] } as unknown as PedagogicalVisit;
describe('Pedagogical Visit planning product boundaries', () => {
  it('uses exactly the three approved types and four lifecycle states', () => { expect(Object.keys(VISIT_TYPE_LABELS)).toEqual(['GUIDANCE', 'TENURE', 'MONITORING']); expect(Object.keys(VISIT_STATUS_LABELS)).toEqual(['SCHEDULED', 'COMPLETED', 'POSTPONED', 'CANCELLED']); });
  it('surprise visits cannot communicate; terminal visits have no mutation actions', () => { for (const visitType of ['GUIDANCE', 'MONITORING'] as const) expect(visitActions({ ...visit, visitType })).not.toContain('COMMUNICATE'); expect(visitActions({ ...visit, visitType: 'TENURE' })).toContain('COMMUNICATE'); expect(visitActions({ ...visit, visitType: 'TENURE', teacherNotifiedAt: 'synthetic' })).not.toContain('COMMUNICATE'); for (const status of ['COMPLETED', 'CANCELLED'] as const) expect(visitActions({ ...visit, status })).toEqual([]); expect(visitActions({ ...visit, status: 'POSTPONED' })).toEqual(['RESCHEDULE', 'CANCEL']); });
  it('real RTL agenda shows surprise privacy, explicit communication only for tenure, and no grading/report controls', () => { const html = renderToStaticMarkup(<VisitAgenda visits={[visit, { ...visit, id: 'tenure', visitType: 'TENURE' }]} onAction={() => undefined} />); expect(html).toContain('dir="rtl"'); expect(html).toContain('زيارة مفاجئة'); expect(html.match(/إبلاغ الأستاذ بالزيارة/g)).toHaveLength(1); for (const label of ['زيارات اليوم', 'الزيارات القادمة', 'الزيارات المنجزة', 'الزيارات المؤجلة', 'الزيارات الملغاة', 'رزنامة الزيارات']) expect(html).toContain(label); expect(html).not.toContain('pedagogicalGrade'); expect(html).not.toContain('طباعة التقرير'); });
  it('scheduling integrates into existing dossier without replacing its card/timetable/print', () => { const source = readFileSync('src/components/informationCard/InspectorSupervisionDossier.tsx', 'utf8'); expect(source).toContain('<PedagogicalVisitPlanner'); expect(source).toContain('slots={data.weeklySchedule}'); for (const original of ['<InformationCardFields', '<InspectorWeeklyTimetable', '<OfficialInformationCardPrint']) expect(source).toContain(original); const weekly = readFileSync('src/components/schedule/InspectorWeeklyTimetable.tsx', 'utf8'); expect(weekly).toContain('<WeeklyTimetableView'); expect(weekly).toContain('readOnly'); });
});
