import React from 'react';
import { CARD_SECTIONS, ADMINISTRATIVE_STATUSES, type CardSnapshot } from '../../types/informationCard';
import { safeCardPhoto } from './OfficialInformationCardPrint';

export function InformationCardFields({ snapshot, onChange }: { snapshot: CardSnapshot; onChange?: (value: CardSnapshot) => void }) {
  const updateExtra = (key: string, value: string) => onChange?.({ ...snapshot, extra: { ...snapshot.extra, [key]: value } });
  const input = (label: string, value: string, update?: (value: string) => void, type = 'text') => <label key={label} className="block text-sm font-bold text-slate-700">{label}<input aria-label={label} type={type} readOnly={!update} value={value} onChange={(e) => update?.(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 font-normal text-slate-900" /></label>;
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-black">الهوية والانتساب</h2>{safeCardPhoto(snapshot.identity.avatar) && <img src={safeCardPhoto(snapshot.identity.avatar)} alt="الصورة الشخصية للحساب" className="mb-4 h-24 w-20 rounded-xl object-cover" />}<div className="grid gap-4 md:grid-cols-2">
      {(['lastName', 'firstName', 'birthDate', 'phone'] as const).map((key, index) => input(['اللقب', 'الاسم', 'تاريخ الازدياد', 'رقم الهاتف'][index], snapshot.identity[key], onChange ? (value) => onChange({ ...snapshot, identity: { ...snapshot.identity, [key]: value } }) : undefined, key === 'birthDate' ? 'date' : 'text'))}
      {input('البريد الإلكتروني الخاص', snapshot.identity.email)}{input('المؤسسة الأم', snapshot.identity.institution)}{input('مديرية التربية', snapshot.identity.directorate)}{input('المقاطعة التفتيشية', snapshot.identity.district)}
    </div><p className="mt-4 text-xs text-slate-500">الانتساب والبريد والصورة من حسابك الحالي. يُطلب تغيير المقاطعة عبر مسار الإسناد في الإعدادات.</p></section>
    {CARD_SECTIONS.map((section) => <section key={section.title} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-black">{section.title}</h2><div className="grid gap-4 md:grid-cols-2">
      {section.fields.map((field) => { const [key, label] = field; const type = field.length > 2 ? field[2] : 'text'; const value = String(snapshot.extra[key] || ''); return key === 'otherInformation' ? <label key={key} className="text-sm font-bold md:col-span-2">{label}<textarea aria-label={label} readOnly={!onChange} maxLength={450} value={value} onChange={(e) => updateExtra(key, e.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label> : input(label, value, onChange ? (value) => updateExtra(key, value) : undefined, type); })}
      {section.title === 'التعيين والوضعية الإدارية' && <label className="text-sm font-bold">الوضعية الإدارية<select aria-label="الوضعية الإدارية" disabled={!onChange} value={String(snapshot.extra.administrativeStatus || '')} onChange={(e) => updateExtra('administrativeStatus', e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="">لم تحدد</option>{ADMINISTRATIVE_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label>}
    </div></section>)}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">المؤهلات</h2><p className="my-2 text-xs text-slate-500">حتى خمسة مؤهلات، وفق عدد أسطر الاستمارة الرسمية.</p>
      {snapshot.extra.qualifications.map((qualification, index) => <div key={index} className="mb-3 grid gap-3 rounded-xl bg-slate-50 p-3 md:grid-cols-4">{(['certificate', 'issuer', 'date'] as const).map((key, fieldIndex) => input(['الشهادة', 'مصدرها', 'تاريخها'][fieldIndex], qualification[key], onChange ? (value) => { const qualifications = snapshot.extra.qualifications.map((row, i) => i === index ? { ...row, [key]: value } : row); onChange({ ...snapshot, extra: { ...snapshot.extra, qualifications } }); } : undefined, key === 'date' ? 'date' : 'text'))}{onChange && <button type="button" className="text-sm font-bold text-red-700" onClick={() => onChange({ ...snapshot, extra: { ...snapshot.extra, qualifications: snapshot.extra.qualifications.filter((_, i) => i !== index) } })}>حذف المؤهل</button>}</div>)}
      {onChange && snapshot.extra.qualifications.length < 5 && <button type="button" className="rounded-xl bg-emerald-50 px-4 py-2 font-bold text-emerald-800" onClick={() => onChange({ ...snapshot, extra: { ...snapshot.extra, qualifications: [...snapshot.extra.qualifications, { certificate: '', issuer: '', date: '' }] } })}>إضافة مؤهل</button>}
    </section>
  </div>;
}
